name: Release

on:
  workflow_dispatch:
    inputs:
      updateType:
        description: Release type
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  changelog:
    uses: ExEr7um/workflows/.github/workflows/changelog.yml@v0.9.1
    with:
      updateType: ${{ inputs.updateType }}
