name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ExEr7um/workflows/.github/workflows/frontend-lint.yml@v0.9.1

  typecheck:
    uses: ExEr7um/workflows/.github/workflows/frontend-typecheck.yml@v0.9.1

  test:
    uses: ExEr7um/workflows/.github/workflows/frontend-test.yml@v0.9.1
