name: Publish to VSCode Marketplace

on:
  workflow_run:
    workflows: [Release]
    types: [completed]

jobs:
  publish:
    uses: ExEr7um/workflows/.github/workflows/publish-vscode.yml@v0.7.0
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
