name: Publish to Marketplaces

on:
  workflow_run:
    workflows: [Release]
    types: [completed]

jobs:
  publish:
    uses: ExEr7um/workflows/.github/workflows/publish-vscode.yml@v0.10.0
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
