name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Changelog and GH Release
        run: |
          npx changelogen@latest --release --push -r ${{ inputs.version }}
          npx changelogen@latest gh release --token ${{ secrets.GITHUB_TOKEN }}

      - name: Release VS Code Package
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          npx @vscode/vsce@latest publish
